export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";
export const CREATE_CONTACT_RESET = "CREATE_CONTACT_RESET";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";
export const DELETE_CONTACT_RESET = "DELETE_CONTACT_RESET";

export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const ALL_CONTACT_SUCCESS = "ALL_CONTACT_SUCCESS";
export const ALL_CONTACT_FAIL = "ALL_CONTACT_FAIL";

export const SINGLE_CONTACT_REQUEST = "SINGLE_CONTACT_REQUEST";
export const SINGLE_CONTACT_SUCCESS = "SINGLE_CONTACT_SUCCESS";
export const SINGLE_CONTACT_FAIL = "SINGLE_CONTACT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";